export const defaultState = {
	sessionNum: 0,
	numQuestions: 0,
	fontSize: "medium",
	questionAns: "",
	questionAnsSum: "",
	questions: "",
	questionSum: "",
	Anagram: {
	Anagram_lunches: {
			title: "Healthier School Lunches",
			numOfText:  5,
			text1: "Another reason is that not all students like the same food, so students need more choices.",
			text2: "That's why I think healthier food, more choices, and more food would make our school lunches better.",
			text3: "One reason is that students need healthier food to stay healthy.",
			text4: "I believe that students should get better lunches at school.",
			text5: "Finally, some students are still hungry after lunch, so each student should get more food.",
			text6: " ",
			fullAnswer: ["35214"],
			partAnswer: ["34215"],
			lessAnswer: ["05010"],
			audio: "../Site/audio/Anagram_lunches.mp3",
	},
	Anagram_pets: {
			title: "Pets at school",
			numOfText:  6,
			text1: "In conclusion, pets should be allowed at school to help students relax, be happy and learn more.",
			text2: "Furthermore, students can learn a lot from different pets, like dogs, cats, or birds.",
			text3: "Students should be allowed to bring their pets to school.",
			text4: "First, pets can make students happy during their classes.",
			text5: "Some people think pets in the classroom will be bad for learning.",
			text6: "I disagree because pets can help students relax and learn better.",
			fullAnswer: ["631245", "653412"],
			partAnswer: ["600045", "600012", "630200", "650400"],
			lessAnswer: ["601000"],
			audio: "../Site/audio/Anagram_pets.mp3",
	},
	Anagram_cellphones: {
			title: "Cell Phones!",
			numOfText:  6,
			text1: "Conversely, other people say that cell phones should not be allowed in schools because they distract students.",
			text2: "I disagree with that because students need to learn how to focus in class even if they have their cell phones.",
			text3: "In conclusion, I believe cell phones are useful during school classes to use important apps and to learn to stay focused.",
			text4: "In particular, the calculator in the cell phone is easy to use and, so, students will not have to spend more money to buy a calculator for class.",
			text5: "Cell phones have many important applications, such as the calculator.",
			text6: "I think that students should be allowed to use cell phones during school.",
			fullAnswer: ["456321", "236541"],
			partAnswer: ["006001"],
			lessAnswer: [" "],
			audio: "../Site/audio/Anagram_cellphones.mp3",
	},
	Anagram_rain: {
			title: "Rain",
			numOfText:  3,
			text1: "If you do not have rain boots, your feet will get wet when you walk to school.",
			text2: "This is why school should be closed when it rains.",
			text3: "I think that there should be no school when it rains.",
			text4: " ",
			text5: " ",
			text6: " ",
			fullAnswer: ["312"],
			partAnswer: [" "],
			lessAnswer: [" "],
			audio: "../Site/audio/Anagram_rain.mp3",
	},
	},
	Connect_pic_asaconsequence: {
		text: "During the class trip, the bus broke down. __________, students were not able to go to the museum.",
		text1: "During the class trip, the bus broke down. ",
		text2: ", students were not able to go to the museum.",
		choice: ["As a consequence", "Likewise", "However", "Otherwise"],
		answer:  1,
		picture1: require("../Site/Images/Connect_pic_asaconsequence_1.png"),
		picture2: require("../Site/Images/Connect_pic_asaconsequence_2.png"),
		audio: "../Site/audio/Connect_pic_asaconsequence.mp3",
	},
	Connect_pic_asaresult: {
		text: "Kim was sick. ________, she stayed home and did not go to school.",
		text1: "Kim was sick. ",
		text2: ", she stayed home and did not go to school.",
		choice: ["Otherwise", "Yet", "In contrast", "As a result"],
		answer:  4,
		picture1: require("../Site/Images/Connect_pic_asaresult_1.png"),
		picture2: require("../Site/Images/Connect_pic_asaresult_2.png"),
		audio: "../Site/audio/Connect_pic_asaresult.mp3",
	},
	Connect_pic_forinstance: {
		text: "Many schools offer team sports for their students. _________, students at my school can be part of our soccer team.",
		text1: "Many schools offer team sports for their students. ",
		text2: ", students at my school can be part of our soccer team.",
		choice: ["On the other hand", "In conclusion", "For instance", "In spite of that"],
		answer:  3,
		picture1: require("../Site/Images/Connect_pic_forinstance_1.png"),
		picture2: require("../Site/Images/Connect_pic_forinstance_2.png"),
		audio: "../Site/audio/Connect_pic_forinstance.mp3",
	},
	Connect_pic_therefore_A: {
		text: "Nick's team won the football game; ________ Nick and his father are excited.",
		text1: "Nick's team won the football game; ",
		text2: " Nick and his father are excited.",
		choice: ["on the other hand", "yet", "however", "therefore"],
		answer:  4,
		picture1: require("../Site/Images/Connect_pic_therefore_A_1.png"),
		picture2: require("../Site/Images/Connect_pic_therefore_A_2.png"),
		audio: "../Site/audio/Connect_pic_therefore_A.mp3",
	},
	Connect_pic_similarly: {
		text: "Grapes come in many different colors. _________, roses also come in many different colors.",
		text1: "Grapes come in many different colors. ",
		text2: ", roses also come in many different colors.",
		choice: ["Because", "But", "However", "Similarly"],
		answer:  4,
		picture1: require("../Site/Images/Connect_pic_similarly_1.png"),
		picture2: require("../Site/Images/Connect_pic_similarly_2.png"),
		audio: "../Site/audio/Connect_pic_similarly.mp3",
	},
	Connect_pic_nevertheless: {
		text: "Sam broke his leg; ________, he continues to play baseball.",
		text1: "Sam broke his leg; ",
		text2: ", he continues to play baseball.",
		choice: ["consequently", "nevertheless", "namely", "thus"],
		answer:  2,
		picture1: require("../Site/Images/Connect_pic_nevertheless_1.png"),
		picture2: require("../Site/Images/Connect_pic_nevertheless_2.png"),
		audio: "../Site/audio/Connect_pic_nevertheless.mp3",
	},
	Connect_pic_whereas_B: {
		text: "A ladybug has 6 legs,________ a centipede has 100 legs.",
		text1: "A ladybug has 6 legs, ",
		text2: " a centipede has 100 legs.",
		choice: ["likewise", "whether", "whereas", "moreover"],
		answer:  3,
		picture1: require("../Site/Images/Connect_pic_whereas_B_1.png"),
		picture2: require("../Site/Images/Connect_pic_whereas_B_2.png"),
		audio: "../Site/audio/Connect_pic_whereas_B.mp3",
	},
	Connect_pic_consequently: {
		text: "Brad studied hard for the test. ________ he got a good grade.",
		text1: "Brad studied hard for the test. ",
		text2: " he got a good grade.",
		choice: ["In contrast", "Even though", "Consequently", "Nonetheless"],
		answer:  3,
		picture1: require("../Site/Images/Connect_pic_consequently_1.png"),
		picture2: require("../Site/Images/Connect_pic_consequently_2.png"),
		audio: "../Site/audio/Connect_pic_consequently.mp3",
	},
	Connect_sent_nonetheless_B: {
		text1: "It started to rain during school recess. ",
		text2: "Nonetheless, ",
		choice: [
			"the students continued to play outside.",
			"the students decided to go inside.",
			"the students got wet.",
		],
		answer:  1,
		audio: "../Site/audio/Connect_sent_nonetheless_B.mp3",
	},
	Connect_sent_however: {
		text1: "The day was sunny and warm; ",
		text2: "however, ",
		choice: [
			"everybody was at the beach.",
			"it was summer time.",
			"there was a strong wind.",
		],
		answer:  3,
		audio: "../Site/audio/Connect_sent_however.mp3",
	},
	Connect_sent_incontrast: {
		text1: "Cats like to eat fish. ",
		text2: "In contrast, ",
		choice: [
			"cats like to eat tuna fish.",
			"dogs like to chew bones.",
			"cats eat food made of fish.",
		],
		answer:  2,
		audio: "../Site/audio/Connect_sent_incontrast.mp3",
	},
	Connect_sent_moreover: {
		text1: "We can get books and magazines from our library. ",
		text2: "Moreover, ",
		choice: [
			"we cannot eat in the library.",
			"we can get videos.",
			"we cannot get video games.",
		],
		answer:  2,
		audio: "../Site/audio/Connect_sent_moreover.mp3",
	},
	Anaphora_olympicgames: {
		text1: "During the Olympic Games, countries from around the world send athletes to compete in various sporting events. ",
		keyword: "These competitions",
		text2: "are divided into two categories: winter and summer.",
		choice: [
			"countries from around the world",
			"athletes",
			"Olympic Games",
		],
		answer:  3,
		audio: "../Site/audio/Anaphora_olympicgames.mp3",
	},
	Anaphora_material: {
		text1: "Major volcanic eruptions release huge quantities of gases and ash into the air. ",
		keyword: "These materials",
		text2: "can stay in the upper atmosphere for months or years.",
		choice: [
			"volcanic eruptions",
			"huge quantities",
			"gases and ash",
		],
		answer:  3,
		audio: "../Site/audio/Anaphora_material.mp3",
	},
	Anaphora_animals: {
		text1: "During the school trip to the zoo, many of the students noticed that the animals were all sleeping. Mrs. John told the students that ",
		keyword: "they",
		text2: "are probably tired.",
		choice: [
			"the animals",
			"the students",
			"the visitors",
		],
		answer:  1,
		audio: "../Site/audio/Anaphora_animals.mp3",
	},
	Anaphora_fest: {
		text1: "  ",
		keyword: "It",
		text2: "has often been compared to Summer Fest, one of the largest festivals in the South. Stuartville's streets are as crowded as they are during Summer Fest. Since it began last week, three million people have attended the Stuartville Fisherman's Festival.",
		choice: [
			"Summer Fest",
			"one of the largest festivals",
			"Stuartville Fisherman's Festival",
		],
		answer:  3,
		audio: "../Site/audio/Anaphora_fest.mp3",
	},
	Anaphora_telescope: {
		text1: "The scientist worked hard to get the telescope ready. She worked for months in her lab. Finally, the day of the meteor shower, ",
		keyword: "the project",
		text2: "was completed.",
		choice: [
			"get the telescope ready",
			"the meteor shower",
			"her lab",
		],
		answer:  1,
		audio: "../Site/audio/Anaphora_telescope.mp3",
	},
	Anaphora_voting: {
		text1: "In the United States and in some other countries, citizens choose the president by voting. Whether or not the system works perfectly, ",
		keyword: "it",
		text2: "is better than a system in which citizens do not vote.",
		choice: [
			"the United States",
			"choosing the president by voting",
			"a system in which citizens do not vote",
		],
		answer:  2,
		audio: "../Site/audio/Anaphora_voting.mp3",
	},
	Anaphora_explorer: {
		text1: "Scott's team and Johnson's team tried to reach the top of the tallest mountain. Johnson's team made it to the top first because of ",
		keyword: "this explorer's",
		text2: "leadership.",
		choice: [
			"Scott",
			"team",
			"Johnson",
		],
		answer:  3,
		audio: "../Site/audio/Anaphora_explorer.mp3",
	},
	Anaphora_phenom: {
		text1: "Our planet is made up of many layers of rock. The top layers are formed of solid rock. The deep layer is so hot that some rock melts. Volcanoes are formed when the melted rock pushes its way up through the top layers. ",
		keyword: "This phenomenon",
		text2: "has been broadly studied.",
		choice: [
			"the top layers of solid rock",
			"the melted rock pushes its way up",
			"the deep layer is so hot that rock melts",
		],
		answer:  2,
		audio: "../Site/audio/Anaphora_phenom.mp3",
	},
	Anaphora_covered: {
		text1: "Mars' red color comes from a chemical in its soil. When this chemical touches oxygen, it rusts and becomes red in color. How exactly the entire planet came to be covered in this red soil is a subject of debate among scientists. Some believe that ",
		keyword: "this process",
		text2: "occurred long ago when water still flowed on Mars' surface, spreading the dust across the planet.",
		choice: [
			"a debate among scientists",
			"this chemical touches oxygen",
			"the entire planet came to be covered in red soil",
		],
		answer:  3,
		audio: "../Site/audio/Anaphora_covered.mp3",
	},
	Anaphora_liquid: {
		text1: "Air temperature is measured using thermometers. A thermometer works because the liquid contained in the thermometer expands when ",
		keyword: "it",
		text2: "is heated and contracts when it is cooled.    ",
		choice: [
			"liquid",
			"thermometer",
			"air",
		],
		answer:  1,
		audio: "../Site/audio/Anaphora_liquid.mp3",
	},
	// Section 4
	Morpho_complexity: {
		text1: "The problem is",
		text2: ".",
		keyword: "complexity",
		answer: ["complex"],
			audio: "../Site/audio/Morpho_complexity.mp3",
	},
	Morpho_civility: {
		text1: "The children should be",
		text2: ".",
		keyword: "civility",
		answer: ["civilized", "civilysed", "civilised", "civil"],
			audio: "../Site/audio/Morpho_civility.mp3",
	},
	Morpho_division: {
		text1: "The cake is hard to",
		text2: ".",
		keyword: "division",
		answer: ["divide", "divied"],
			audio: "../Site/audio/Morpho_division.mp3",
	},
	Morpho_expansion: {
		text1: "The business will",
		text2: ".",
		keyword: "expansion",
		answer: ["expand"],
			audio: "../Site/audio/Morpho_expansion.mp3",
	},
	Morpho_availability: {
		text1: "The video will soon be",
		text2: ".",
		keyword: "availability",
		answer: ["availuble", "availible", "availeble", "availoble", "available"],
			audio: "../Site/audio/Morpho_availability.mp3",
	},
	Morpho_cultural: {
		text1: "We love our",
		text2: ".",
		keyword: "cultural",
		answer: ["cultures", "culture"],
			audio: "../Site/audio/Morpho_cultural.mp3",
	},
	Morpho_discrimination: {
		text1: "He works hard not to",
		text2: ".",
		keyword: "discrimination",
		answer: ["discriminate", "discrimonate", "discrimunate", "discrimanate", "discriminait", "discrimonait", "discrimunait", "discrimanait"],
			audio: "../Site/audio/Morpho_discrimination.mp3",
	},
	Morpho_contribution: {
		text1: "How will you",
		text2: "?",
		keyword: "contribution",
		answer: ["contribute"],
			audio: "../Site/audio/Morpho_contribution.mp3",
	},
	Morpho_durability: {
		text1: "This suitcase is",
		text2: ".",
		keyword: "durability",
		answer: ["duruble", "durabul", "durible", "durable"],
			audio: "../Site/audio/Morpho_durability.mp3",
	},
	Morpho_responsive: {
		text1: "She raised her hand to give her",
		text2: ".",
		keyword: "responsive",
		answer: ["response", "respons", "responce"],
			audio: "../Site/audio/Morpho_responsive.mp3",
	},
	Morpho_astronomical: {
		text1: "He loves to learn about",
		text2: ".",
		keyword: "astronomical",
		answer: ["astronomy", "astronemy", "astronimy", "astronamy", "astronumy", "astronemee", "astronimee", "astronamee", "astronumee"],
			audio: "../Site/audio/Morpho_astronomical.mp3",
	},
	// Section 5
	SYNTAX_PICTURES: {
		Syntax_pic_5: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_5a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_5b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_5c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_5d.JPG"),
			audio: "../Site/audio/Syntax_pic_5.mp3",
			answer:  2,
	},
		Syntax_pic_1: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_1a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_1b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_1c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_1d.JPG"),
			audio: "../Site/audio/Syntax_pic_1.mp3",
			answer:  1,
	},
		Syntax_pic_10: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_10a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_10b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_10c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_10d.JPG"),
			audio: "../Site/audio/Syntax_pic_10.mp3",
			answer:  1,
	},
		Syntax_pic_11: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_11a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_11b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_11c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_11d.JPG"),
			audio: "../Site/audio/Syntax_pic_11.mp3",
			answer:  1,
	},
		Syntax_pic_3: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_3a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_3b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_3c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_3d.JPG"),
			audio: "../Site/audio/Syntax_pic_3.mp3",
			answer:  3,
	},
		Syntax_pic_8: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_8a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_8b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_8c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_8d.JPG"),
			audio: "../Site/audio/Syntax_pic_8.mp3",
			answer:  1,
	},
	},
	// Section 6
	DEFINITIONS_AWARENESS: {
		def_aware_clown: {
			text1: "A clown is someone with funny clothes that makes lots of jokes to make adults and children laugh.",
			text2: "A clown is when you dress funny and you make lots of jokes for people to laugh.",
			text3: "A clown is an actor who wears odd clothes and entertains people using jokes and tricks.",
			keyword: "Clown",
			answer: [1, 1, 2, 3],
			audio: "../Site/audio/def_aware_clown.mp3",
	},
		def_aware_confusion: {
			text1: "Confusion is what you feel when you do not know what is going on.",
			text2: "Confusion is the state of being uncertain or unclear about something.",
			text3: "Confusion is when people don't know what to do.",
			keyword: "Confusion",
			answer: [1, 2, 1, 2],
			audio: "../Site/audio/def_aware_confusion.mp3",
	},
		def_aware_debate: {
			text1: "A debate is a discussion of two or more opposing viewpoints.",
			text2: "A debate is when you argue about something with others.",
			text3: "A debate is a thing where people talk and discuss their opinions.",
			keyword: "Debate",
			answer: [2, 1, 1, 1],
			audio: "../Site/audio/def_aware_debate.mp3",
	},
	},
	// Section 7
	EPISTEMIC_MARKERS: {
		rock_from_space: {
			title1: "The Rock is from Space: Sure or Unsure?",
			title2: "Is the rock from space? How sure is each scientist?",
			text1:
				"The scientists ran tests to see if a rock came from space. Based on the results of their tests, some scientists are very sure the rock is from the space and other scientists have doubts. After reading what each scientist said, you decide how sure each scientist is!",
		},
		is_Jessie_coming: {
			title1: "Is Jessie Coming to school today?: Sure or Unsure?",
			title2: "Is Jessie Coming to school today? How sure are Jessie's friends?",
			text1:
				"A group of friends is trying to figure out if Jessie is coming to visit their class today. Some friends are very sure Jessie will come and some friends have doubts. After reading what each friend said, you decide how sure each friend is!",
		},
		epis_obvious: {
			text0: "The scientist thinks:",
			text1: "It is obvious that the rock is from space.",
			text2: "Does this scientist think that the rock comes from space?",
			answer:  1,
			audio: "../Site/audio/epis_obvious.mp3",
			description: "rock_from_space",
			img: "epis_obvious.png",
	},
		epis_acc_certainlynot: {
			text0: "The scientist thinks:",
			text1: "The rock is certainly not from space.",
			text2: "Does this scientist think that the rock comes from space?",
			answer:  4,
			audio: "../Site/audio/epis_acc_certainlynot.mp3",
			description: "rock_from_space",
			img: "epis_acc_certainlynot.png",
	},
		epis_unlikely: {
			text0: "The scientist thinks:",
			text1: "It is unlikely that the rock is from space.",
			text2: "Does this scientist think that the rock comes from space?",
			answer:  3,
			audio: "../Site/audio/epis_unlikely.mp3",
			description: "rock_from_space",
			img: "epis_unlikely.png",
	},
		epis_possible: {
			text0: "The scientist thinks:",
			text1: "It is possible that the rock is from space.",
			text2: "Does this scientist think that the rock comes from space?",
			answer:  2,
			audio: "../Site/audio/epis_possible.mp3",
			description: "rock_from_space",
			img: "epis_possible.png",
	},
		epis_suggest: {
			text0: "The scientist thinks:",
			text1: "Results suggest that the rock is from space.",
			text2: "Does this scientist think that the rock comes from space?",
			answer:  2,
			audio: "../Site/audio/epis_suggest.mp3",
			description: "rock_from_space",
			img: "epis_suggest.png",
	},
		epis_possiblebutunlikely: {
			text0: "The scientist thinks:",
			text1: "It is possible, but unlikely that the rock is from space.",
			text2: "Does this scientist think that the rock comes from space?",
			answer:  3,
			audio: "../Site/audio/epis_possiblebutunlikely.mp3",
			description: "rock_from_space",
			img: "epis_possiblebutunlikely.png",
	},
		epis_presumably: {
			text0: "The scientist thinks:",
			text1: "Presumably, the rock is from space.",
			text2: "Does this scientist think that the rock comes from space?",
			answer:  2,
			audio: "../Site/audio/epis_presumably.mp3",
			description: "rock_from_space",
			img: "epis_presumably.png",
	},
		epis_acc_unquestion: {
			text0: "The scientist thinks:",
			text1: "It is unquestionable that the rock is from space.",
			text2: "Does this scientist think that the rock comes from space?",
			answer:  1,
			audio: "../Site/audio/epis_acc_unquestion.mp3",
			description: "rock_from_space",
			img: "epis_acc_unquestion.png",
	},
		epis_acc_unlikelybut: {
			text0: "The scientist thinks:",
			text1: "It is unlikely but possible that the rock is from space.",
			text2: "Does this scientist think that the rock comes from space?",
			answer:  3,
			audio: "../Site/audio/epis_acc_unlikelybut.mp3",
			description: "rock_from_space",
			img: "epis_acc_unlikelybut.png",
	},
	},
	// Section 8
	METALINGUISTIC: {
		meta_disagreeing: {
			newspaper: "Newspaper:",
			news: "Students need recess to have fun and relax at school.",
			people: "Jamie:",
			idea: "I don't think so. Students do not need recess because they can have fun after school.",
			ask: "In the sentences above, Jamie is ...",
			type: "bubble",
			img: "meta_disagreeing.png",
			options: [
				"introducing the newspaper's idea",
				"clarifying the newspaper's idea",
				"agreeing with the newspaper's idea",
				"disagreeing with the newspaper's idea",
			],
			answer:  4,
			audio: "../Site/audio/meta_disagreeing.mp3",
	},
		meta_exaggeration: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Jenny:",
			idea: "Yes, music makes all students happier than anything else in the world.",
			ask: "In the sentence above, Jenny is giving...",
			type: "bubble",
			img: "meta_exaggeration.png",
			options: [
				"a disagreement",
				"an exaggeration",
				"a clarification",
				"an explanation",
			],
			answer:  2,
			audio: "../Site/audio/meta_exaggeration.mp3",
	},
		meta_precise: {
			newspaper: "Newspaper:",
			news: "Recess is the perfect time for students to build friendships.",
			people: "Laura's essay:",
			idea: "In the U.S., 92% of elementary school teachers reported that recess helps students make friends.",
			ask: "In her essay, Laura presents...",
			type: "pencil",
			img: "meta_precise.png",
			options: [
				"a vague statement",
				"a contradictory statement",
				"a redundant statement",
				"a precise statement",
			],
			answer:  4,
			audio: "../Site/audio/meta_precise.mp3",
	},
		meta_contradictingB: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Alexa's essay:",
			idea: "I disagree. Most students don't like music because it's too loud.",
			ask: "In her essay, Alexa is...",
			type: "pencil",
			img: "meta_contradictingB.png",
			options: [
				"emphasizing the newspaper's idea",
				"contradicting the newspaper's idea",
				"restating the newspaper's idea",
				"underscoring the newspaper's idea",
			],
			answer:  2,
			audio: "../Site/audio/meta_contradictingB.mp3",
	},
		meta_inconsistent: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Maria's essay:",
			idea: "Music makes students sad. Most students are happy when they listen to music.",
			ask: "In her essay, Maria presents...",
			type: "pencil",
			img: "meta_inconsistent.png",
			options: [
				"coherent information",
				"credible information",
				"hypothetical information",
				"inconsistent information",
			],
			answer:  4,
			audio: "../Site/audio/meta_inconsistent.mp3",
	},
		meta_supportclaim: {
			newspaper: "Newspaper:",
			news: "Students need recess to have fun and relax at school.",
			people: "Paul:",
			idea: "I agree. In addition, recess is an important time to make friends.",
			ask: "Paul is giving ...",
			type: "bubble",
			img: "meta_supportclaim.png",
			options: [
				"a counterclaim",
				"some evidence",
				"a conclusion",
				"another supporting claim",
			],
			answer:  4,
			audio: "../Site/audio/meta_supportclaim.mp3",
	},
		meta_quoting: {
			newspaper: "Newspaper:",
			news: "Recess is the perfect time for students to make friends.",
			people: "Cindy's essay:",
			idea: "Students should have recess because it \"is the perfect time for students to make friends.\"",
			ask: "In her essay, Cindy is...",
			type: "pencil",
			img: "meta_quoting.png",
			options: [
				"opposing the newspaper's idea",
				"quoting the newspaper's idea",
				"describing the newspaper's idea",
				"exaggerating the newspaper's idea",
			],
			answer:  2,
			audio: "../Site/audio/meta_quoting.mp3",
	},
		meta_fallacy: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Ebony's essay:",
			idea: "Pat was crying in music class, so music makes people cry.",
			ask: "In the sentence above, Ebony presents...",
			type: "pencil",
			img: "meta_fallacy.png",
			options: [
				"a fallacy",
				"an understatement",
				"a paraphrase",
				"a citation",
			],
			answer:  1,
			audio: "../Site/audio/meta_fallacy.mp3",
	},
		meta_contradictingA: {
			newspaper: "Newspaper:",
			news: "Students need recess to have fun and relax at school.",
			people: "Jamie:",
			idea: "I don't think so. Students do not need recess because they can have fun after school.",
			ask: "Jamie is ...",
			type: "bubble",
			img: "meta_contradictingA.png",
			options: [
				"emphasizing the newspaper's idea",
				"supporting the newspaper's idea",
				"contradicting the newspaper's idea",
				"misrepresenting the newspaper's idea",
			],
			answer:  3,
			audio: "../Site/audio/meta_contradictingA.mp3",
	},
	},
};
 
export default (state = defaultState, action) => {
	if (action.type === "add_sessionNum") {
		const newState = JSON.parse(JSON.stringify(state));
		newState.sessionNum = newState.sessionNum + 1;
		return newState;
	}
	if (action.type === "update_fontSize") {
		const newState = JSON.parse(JSON.stringify(state));
		newState.fontSize = action.value;
		// console.log(action.value)
		return newState;
	}
	if (action.type === "ANSWER_QUESTION") {
		const newState = JSON.parse(JSON.stringify(state));
		if (newState.questionAns === "") {
			newState.questionAns = action.questionAns;
			newState.questionAnsSum = action.questionAns;
			newState.questions = action.question;
			newState.questionSum = action.question;
		} else {
			newState.questionAns += "," + action.questionAns;
			newState.questionAnsSum += "+" + action.questionAns;
			newState.questions += "," + action.question;
			newState.questionSum += "+" + action.question;
		}
		newState.numQuestions += 1;
		return newState;
	}
	if (action.type === "CLEAR_NUM_QUESTION") {
		const newState = JSON.parse(JSON.stringify(state));
		newState.numQuestions = 0;
		return newState;
	}
 
	return state;
};
